select
EMPLOYEE_CODE, MTG_LOC, mtg_tag, TM_OF_DY_IND, MTG_DTE, --MTG_ATTCHMT_FLG
POSITION_CODE, MANAGER_CODE, BRANCH_CODE, ORGANIZATION_CODE, BIRTH_DATE, GENDER_CODE, 
EMPLOYEE_RT_TIER, LEFT(('20160101'- CAST(date(BIRTH_DATE) AS INTEGER)),2) AS employee_Age,
MTG_CT_TTL,
MTG_DUR_TTL, (MTG_DUR_TTL*EMPLOYEE_RT_TIER) as MTG_COST,
MTG_INVTD_TTL,
MTG_ACCPTD_TTL,
MTG_DCLND_TTL
from( -------------

select a13.EMPLOYEE_CODE, a13.MTG_LOC, a13.mtg_tag, a13.TM_OF_DY_IND, a13.MTG_DTE, --MTG_ATTCHMT_FLG
a14.POSITION_CODE, MANAGER_CODE, BRANCH_CODE, ORGANIZATION_CODE, BIRTH_DATE, GENDER_CODE, 
a15.EMPLOYEE_RT_TIER,--(DATE-a14.BIRTH_DATE) AS EMPLOYEE_AGE,
sum(a13.mtg_ct) MTG_CT_TTL,
sum(a13.mtg_dur_ttl) MTG_DUR_TTL,
sum(a13.invtd_ttl) MTG_INVTD_TTL,
sum(a13.accptd_ttl) MTG_ACCPTD_TTL,
sum(a13.dclnd_ttl) MTG_DCLND_TTL

from(
SELECT
mtg_loc, mtg_tag, employee_code, mtg_dte, tm_of_dy_ind, mtg_ct, mtg_dur_ttl, accptd_ttl, dclnd_ttl, invtd_ttl
FROM DASH7934.MTG_DTE_EMPLOYEE_LOC
) a13

join ( 
SELECT a11.EMPLOYEE_CODE, a11.GENDER_CODE, a11.DATE_HIRED, a11.TERMINATION_CODE, a11.BIRTH_DATE,
a12.EMPLOYEE_HISTORY_CODE, EMPLOYEE_HISTORY_PARENT, RECORD_START_DATE,
a12.RECORD_END_DATE, POSITION_CODE, POSITION_START_DATE, MANAGER_CODE, BRANCH_CODE, ORGANIZATION_CODE
FROM GOSALESHR.EMPLOYEE a11

join GOSALESHR.EMPLOYEE_HISTORY a12 on (a12.EMPLOYEE_CODE=a11.EMPLOYEE_CODE) ) a14 on (a14.EMPLOYEE_CODE=a13.EMPLOYEE_CODE)

join DASH7934.EMPLOYEE_RT_TIER_LKP a15 on (a15.EMPLOYEE_CODE=a13.EMPLOYEE_CODE)

group by a13.EMPLOYEE_CODE, a13.MTG_LOC, a13.mtg_tag, a13.TM_OF_DY_IND, MTG_DTE, --MTG_ATTCHMT_FLG
a14.POSITION_CODE, MANAGER_CODE, BRANCH_CODE, ORGANIZATION_CODE, BIRTH_DATE, GENDER_CODE, 
a15.EMPLOYEE_RT_TIER--, EMPLOYEE_AGE
) AA ------
